const data = {
    products: [
        {
            name: 'Nike Apolo Shirt',
            slug: 'nike-apolo shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numberReviews: 10,
            description: 'Top quality shirt',
        },
        {
            name: 'Adidas Fit Shirt',
            slug: 'adidas-apolo-shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 250,
            countInStock: 20,
            brand: 'Adidas',
            rating: 4.0,
            numberReviews: 10,
            description: 'Top quality shirt',
        },
        {
            name: 'Nike Slim Pant',
            slug: 'nike-slim-pant',
            category: 'Pants',
            image: '/images/p3.jpg',
            price: 25,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numberReviews: 14,
            description: 'Top quality shirt',
        },
        {
            name: 'Adidas Fit Pant',
            slug: 'adidas-fit-pant',
            category: 'Pant',
            image: '/images/p4.jpg',
            price: 65,
            countInStock: 5,
            brand: 'Puma',
            rating: 4.5,
            numberReviews: 10,
            description: 'Top quality shirt',
        },
    ]
};
export default data;